### ISSUE TITLE
Kasih tiktod dl dong stah><

### ISSUE THREAD

**Issue by alanwildan** [Hexagonz/SELF-HX#2]

**Comment by alanwildan** [comment]
Plisss :)

**Comment by ZefianAlfian** [comment]
`npm i zrapi`

`const zrapi = require("zrapi");
zrapi.keeptiktok(urlTiktok)
.then(data => console.log(data))
.catch(e => console.log(e));`

**Comment by alanwildan** [comment]
Aduh makasih anyink
