### ISSUE TITLE
npm i canvas error 

### ISSUE THREAD

**Issue by Len-cmd** [Hexagonz/SELF-HX#7]
npm WARN SELF-HX@1.0.0 No description
npm WARN SELF-HX@1.0.0 No repository field.

npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../detect-libc/bin/detect-libc.js
npm ERR! dest /storage/emulated/0/Music/SELF-HX/node_modules/.bin/detect-libc
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../detect-libc/bin/detect-libc.js' -> '/storage/emulated/0/Music/SELF-HX/node_modules/.bin/detect-libc'
npm ERR!  [OperationalError: EPERM: operation not permitted, symlink '../detect-libc/bin/detect-libc.js' -> '/storage/emulated/0/Music/SELF-HX/node_modules/.bin/detect-libc'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, symlink '../detect-libc/bin/detect-libc.js' -> '/storage/emulated/0/Music/SELF-HX/node_modules/.bin/detect-libc'] {
npm ERR!     errno: -1,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../detect-libc/bin/detect-libc.js',
npm ERR!     dest: '/storage/emulated/0/Music/SELF-HX/node_modules/.bin/detect-libc'
npm ERR!   },
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../detect-libc/bin/detect-libc.js',
npm ERR!   dest: '/storage/emulated/0/Music/SELF-HX/node_modules/.bin/detect-libc',
npm ERR!   parent: 'tes'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-05-21T10_01_37_940Z-debug.log

:v

**Comment by Hexagonz** [comment]
canvas kalo ga salah ga bisa di termux
